services:
    web-app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        container_name: web-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - mailpit
    pgsql:
        image: 'postgres:17'
        container_name: pgsql
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    mongodb:
      image: 'mongo:latest'
      container_name: mongodb
      environment:
        - 'MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-admin}'
        - 'MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password}'
        - 'MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-my_database}'
      volumes:
        - 'sail-mongodb:/data/db'
        - 'sail-mongodb-config:/data/configdb'
      ports:
        - '${FORWARD_MONGODB_PORT:-27017}:27017'
      networks:
        - sail
      healthcheck:
        test:
          - CMD
          - mongosh
          - '--eval=db.adminCommand("ping")'
        retries: 3
        timeout: 5s
        interval: 10s
        start_period: 30s

    adminer:
      image: dockette/adminer:full
      container_name: adminer
      ports:
        - '8000:80'
      networks:
        - sail
      depends_on:
        - mongodb
        - pgsql

networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-mongodb-config:
        driver: local
    sail-mongodb:
        driver: local
