<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="bg-background font-inria">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Recipe Finder - Turn your ingredients into delicious meals and reduce food waste">
        <title>Privacy Policy</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <div class="max-w-4xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-gray-900 mb-8">Imprint</h1>
            <div>
                Note: This privacy policy is present only for the sake of completeness.
                This is an example and was generated by AI.
            </div>
            <div class="space-y-8">
                <!-- Company Information -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">Information pursuant to § 5 TMG</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <div class="space-y-2">
                            <p>Recipe Finder GmbH</p>
                            <p>Sample Street 123</p>
                            <p>12345 Sample City</p>
                            <p>Germany</p>
                        </div>
                    </div>
                </section>

                <!-- Contact Information -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">1. Contact Information</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <div class="space-y-2">
                            <p>Phone: 01234 567890</p>
                            <p>Email: recipefinder@example.com</p>
                        </div>
                    </div>
                </section>

                <!-- Registration -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">2. Registration Information</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <div class="space-y-2">
                            <p>Registered at the Commercial Register of {{ $local_court ?? '[Local Court Location]' }}</p>
                            <p>Registration Number: {{ $registration_number ?? '[HRB number]' }}</p>
                            <p>VAT ID Number according to §27a Value Added Tax Act: {{ $vat_number ?? '[VAT number]' }}</p>
                        </div>
                    </div>
                </section>

                <!-- Content Responsibility -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">3. Responsible for Content (§ 55 Abs. 2 RStV)</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <div class="space-y-2">
                            <p>Recipe Finder GmbH</p>
                            <p>Sample Street 123</p>
                            <p>12345 Sample City</p>
                            <p>Germany</p>
                        </div>
                    </div>
                </section>

                <!-- Dispute Resolution -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">4. Dispute Resolution</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p>The European Commission provides a platform for online dispute resolution (OS):<br>
                        <a href="https://ec.europa.eu/consumers/odr" class="text-blue-600 hover:text-blue-800">https://ec.europa.eu/consumers/odr</a></p>
                        <p class="mt-4">We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.</p>
                    </div>
                </section>

                <!-- Liability -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">5. Liability for Content</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p>As a service provider, we are responsible for our own content on these pages according to § 7 paragraph 1 TMG under the general laws. According to §§ 8 to 10 TMG, we are not obligated to monitor transmitted or stored third-party information or to investigate circumstances that indicate illegal activity.</p>
                        <p class="mt-4">Obligations to remove or block the use of information under the general laws remain unaffected. However, liability in this regard is only possible from the point in time at which a concrete infringement of the law becomes known. Upon becoming aware of corresponding legal violations, we will remove this content immediately.</p>
                    </div>
                </section>

                <!-- Copyright -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">6. Copyright</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p>The contents and works on these pages created by the site operators are subject to German copyright law. The reproduction, editing, distribution, and any kind of exploitation outside the limits of copyright law require the written consent of the respective author or creator. Downloads and copies of these pages are only permitted for private, non-commercial use.</p>
                    </div>
                </section>

                <!-- Last Update -->
                <section class="prose max-w-none">
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p>Last updated: {{ date('m/d/Y') }}</p>
                    </div>
                </section>
            </div>
        </div>
    </body>
    <x-footer backgroundClasses="bg-background text-primary"/>
</html>
