<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="bg-background font-inria">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Recipe Finder - Turn your ingredients into delicious meals and reduce food waste">
    <title>Privacy Policy</title>
    <!-- Styles -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
    <body>
        <div class="max-w-4xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
            <div>
                Note: This privacy policy is present only for the sake of completeness.
                This is an example and was generated by AI.
            </div>
            <div class="space-y-8">
                <!-- Section 1: General Information -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">1. General Information and Mandatory Disclosures</h2>

                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <h3 class="text-xl font-semibold text-gray-900 mb-4">Responsible Entity</h3>
                        <div class="space-y-2">
                            <p>Recipe Finder GmbH</p>
                            <p>Sample Street 123, 12345 Sample City</p>
                            <p>recipefinder@example.com</p>
                            <p>01234 567890</p>
                        </div>
                    </div>
                </section>

                <!-- Section 2: Data Collection -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">2. Data Collection on our Website</h2>

                    <div class="space-y-6">
                        <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                            <h3 class="text-xl font-semibold text-gray-900 mb-4">Registration on our Website</h3>
                            <p class="mb-4">When registering for the use of our personalized services, the following personal data is collected:</p>
                            <ul class="list-disc pl-6 mb-4">
                                <li>Name</li>
                                <li>Email address</li>
                            </ul>
                            <p>This data is collected to:</p>
                            <ul class="list-disc pl-6">
                                <li>Provide you with a secure login area</li>
                                <li>Enable you to create recipes</li>
                                <li>Inform you about technical or legal changes when necessary</li>
                            </ul>
                        </div>

                        <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                            <h3 class="text-xl font-semibold text-gray-900 mb-4">Cookies</h3>
                            <p class="mb-4">Our website only uses technically necessary cookies. These cookies are required for the operation of the website and cannot be deactivated in your system.</p>
                            <p>The following technically necessary cookies are used:</p>
                            <ul class="list-disc pl-6">
                                <li>Session cookies for login functionality</li>
                                <li>Cookies for storing language settings</li>
                                <li>Cookies for ensuring website security</li>
                            </ul>
                        </div>
                    </div>
                </section>

                <!-- Section 3: Your Rights -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">3. Your Rights</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p class="mb-4">You have the following rights:</p>
                        <ul class="list-disc pl-6">
                            <li>Right to information (Art. 15 GDPR)</li>
                            <li>Right to rectification (Art. 16 GDPR)</li>
                            <li>Right to erasure (Art. 17 GDPR)</li>
                            <li>Right to restriction of processing (Art. 18 GDPR)</li>
                            <li>Right to data portability (Art. 20 GDPR)</li>
                            <li>Right to object (Art. 21 GDPR)</li>
                        </ul>
                    </div>
                </section>

                <!-- Section 4: Data Security -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">4. Data Security</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p>We implement technical and organizational security measures to protect your personal data against accidental or intentional manipulation, loss, destruction, or access by unauthorized persons. Our security measures are continuously improved in line with technological developments.</p>
                    </div>
                </section>

                <!-- Section 5: Current Status -->
                <section class="prose max-w-none">
                    <h2 class="text-2xl font-semibold text-gray-900 mb-4">5. Currency and Changes to this Privacy Policy</h2>
                    <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                        <p>This privacy policy is currently valid and was last updated on {{ date('m/d/Y') }}.</p>
                        <p class="mt-4">Due to the ongoing development of our website or changes in legal or regulatory requirements, it may become necessary to modify this privacy policy. The current version of the privacy policy can be accessed and retrieved from this website at any time.</p>
                    </div>
                </section>
            </div>
        </div>
    </body>
    <x-footer backgroundClasses="bg-background text-primary"/>
</html>
